INSERT INTO editoras (nome_editora)
VALUES ('Academia'), 
('Alta Life'), 
('Arqueiro'), 
('AVEC Editora'), 
('Biblioteca Azul'), 
('Cia. das Letras'), 
('Camelot Editora'), 
('Citadel'), 
('Editora Vida'), 
('Gente'), 
('Gente Autoridade'), 
('Globo Livros'), 
('HarperCollins'), 
('Intrínseca'), 
('Maquinaria Editorial'), 
('Matrix Editora'), 
('NewPOP'), 
('Outro Planeta'), 
('Pixel'), 
('Prumo'), 
('Rocco'), 
('Sextante'), 
('tatu-bola'), 
('Temporalis'), 
('Unno'), 
('Vélos');