INSERT INTO livros (nome_livro, id_autor, id_editora, id_categoria)
VALUES
('1984', 13, 23, 1),
('A cor que nos separa', 24, 3, 1),
('A empregada', 11, 2, 1),
('A hora da estrela (edição comemorativa)', 4, 20, 1),
('A hipótese do amor', 0, 2, 1),
('A saúde do coração na era da alta performance', 17, 9, 4),
('Arrume a sua cama', 40, 21, 4),
('As 48 leis do poder (capa dura)', 27, 20, 4),
('Café com Deus Pai 2025', 21, 25, 4),
('Café com Jesus', 21, 25, 4),
('CapyVibes', 1, 6, 2),
('Capital inteligente', 37, 9, 3),
('Como desenhar coisas superfofas com Bobbie Goods', 1, 12, 2),
('Como falar bem e ficar rico', 15, 9, 3),
('Cute & Comfy - Capivaras and Friend - azul', 6, 6, 2),
('Cute & Comfy - Capivaras and Friend - azul bebê', 6, 6, 2),
('Cute & Comfy - Capivaras and Friend - rosa', 6, 6, 2),
('Cute & Comfy - Capivaras and Friend - rosa bebê', 6, 6, 2),
('Cute & Comfy - Capivaras and Friend - rosa choque', 6, 6, 2),
('Cute & Comfy - Special Edition - Azul', 6, 6, 2),
('Cute & Comfy - Special Edition - Laranja', 6, 6, 2),
('Cute & Comfy - Special Edition - Roxo', 6, 6, 2),
('Desbloqueie o poder da sua mente', 20, 20, 4),
('Dias frios (Fall Winter)', 1, 12, 2),
('Dias quentes (Spring Summer)', 1, 12, 2),
('Divergente: Guia oficial do filme', 10, 18, 2),
('Do dia para a noite (Day to night)', 1, 12, 2),
('Educação da tristeza', 22, 14, 4),
('Elo Monsters Books: Flow Pack', 9, 18, 2),
('Em nome do povo: Como o casamento entre Estado e Moeda te deixa mais pobre', 37, 7, 3),
('Empreender', 6, 9, 3),
('Engenharia do lucro', 14, 9, 3),
('Entre o ego e o sagrado', 28, 9, 4),
('Eu, empreendedor', 30, 9, 3),
('Hábitos atômicos', 19, 21, 4),
('Isso e aquilo (This & That)', 1, 12, 2),
('Jantar secreto', 32, 20, 1),
('Lidere para o futuro', 16, 9, 3),
('Mais esperto que o diabo', 29, 21, 4),
('Mais esperto que o Diabo 2', 29, 21, 4),
('Melhor que nos filmes', 24, 12, 1),
('O cara que estou a fim não é um cara?! - Volume 1', 36, 16, 1),
('O cara que estou a fim não é um cara?! - Volume 2', 36, 16, 1),
('O diário de uma princesa desastrada', 10, 18, 2),
('O homem que comprou o tempo', 37, 7, 1),
('O parque dos lobos', 32, 20, 1),
('O poder da autorresponsabilidade', 30, 9, 4),
('Os improváveis', 33, 20, 1),
('Pai, me conta a sua história?', 8, 13, 4),
('Prepara... vai!', 39, 6, 4),
('Pressa de futuro', 34, 15, 4),
('Preta Gil: os primeiros 50', 31, 11, 4),
('Quebrando o hábito de ser você mesmo', 20, 20, 4),
('Um amor problemático de verão', 25, 12, 1),
('Um intercâmbio quase perfeito', 25, 12, 1);