INSERT into autores (nome_autor)
VALUES ('Ali Hazelwood'),
('Bobbie Goods'),
('Bruno Perini'),
('Camelot Editora'),
('Clarice Lispector'),
('Cristina Florentino'),
('Daniel Tonetto'),
('Davi Ramos'),
('Elma Van Vliet'),
('Enaldinho'),
('Flora Pinheiro'),
('Freida McFadden'),
('Gabriel Dearo / Manu Digilio'),
('George Orwell'),
('Geraldo Rufino'),
('Giovanni Begossi'),
('Gustavo Borges'),
('Gustavo Michelstaedter Rodrigues'),
('Henrique Prata'),
('James Clear'),
('Joe Dispenza'),
('Junior Rostirola'),
('Kélen Abreu'),
('Leonardo Mack'),
('Lynn Painter'),
('Maidy Lacerda'),
('Marcos Madaleno'),
('Michael Arruda'),
('Mih Tanino'),
('Napoleon Hill'),
('Paulo Vieira'),
('Preta Gil'),
('Raphael Montes'),
('Robert Greene'),
('Rogério Godinho'),
('Sergio Tinen'),
('Sumiko Arai'),
('Thiago Nigro'),
('Valter Hugo Mae'),
('Vinícius Iracet'),
('William H. McRaven');



